defaults:
  - model: default
  - loss: loss
  - data:
      - UoG
      - transform
  - _self_

experiment_name: "Multi-Patch_MLP-Mixer"
num_classes: 6
epochs: 200
learning_rate: 1e-3
batch_size: 32
num_workers: 8
weight_decay: 1e-4
csv_path: "/home/eslab/Vscode/test_model/results"
best_model_path: "/home/eslab/Vscode/test_model/checkpoints"
